### ISSUE TITLE
mathpartir?

### ISSUE THREAD

**Issue by ice1000** [banana-space/btex#11]
有没有写红包的教程

**Comment by rqy2002** [comment]
目前大概只能参考src/lib/init.btx

**Comment by rqy2002** [comment]
数学环境里的东西还没法超出katex处理的范围

**Comment by Trebor-Huang** [comment]
我有动力的话就写，但是
- 我大概没有
- btex现在不能用命令加载新文件（因为主要还是为网站设计）
- 数学公式的处理方法是，先把所有btex宏展开之后送交KaTeX处理，如果你觉得btex宏+原版KaTeX就足够了那也可以
- btex不能用命令直接输出html（因为香蕉空间有mediawiki可以这么做）

**Comment by ice1000** [comment]
可以生成 cfrac，但 mathpartir 的核心功能在我看来是换行等整理一组公式这种性质的东西，除此之外还有 \\ 代替 \quad 等可能无法在 KaTeX 里实现的功能。可能很难搞。

**Comment by abccsss** [comment]
> 数学环境里的东西还没法超出katex处理的范围

理论上是可以超出的，例如目前 `cd` 的实现。但非常麻烦。

**Comment by abccsss** [comment]
我觉得目前不大有这个需求，实现起来麻烦，所以暂时搁置吧。
