### ISSUE TITLE
`\texttt` 不支持

### ISSUE THREAD

**Issue by ice1000** [banana-space/btex#23]
是否考虑支持该字体

**Comment by abccsss** [comment]
原始的想法是以 `\code` 命令代之，以实现代码高亮等功能。`\code` 会自带一个灰色背景，而 `\texttt` 大概是不带背景的等宽字体，但可能不太用得到，比如 markdown 也没有这种功能。大部分情况用户写 `\texttt` 是想要 `\code` 的效果，所以编译错误也可以提醒用户这一点。

**Comment by ice1000** [comment]
原来如此，可否考虑在编译错误里特判一下，加入 "did you mean" 这种功能？

**Comment by abccsss** [comment]
可以，实现起来也不复杂。大概在 `init.btx` 里
```
\tdef\texttt{\@@throw{DID_YOU_MEAN}}
```
然后加入错误信息就可以，我有空可以来做。

**Comment by ice1000** [comment]
非常感谢！
