### ISSUE TITLE
tabular 里面弄个链接就寄了

### ISSUE THREAD

**Issue by ice1000** [banana-space/btex#26]
![image](https://user-images.githubusercontent.com/16398479/212094294-6bdebdc2-9f5b-4ac7-8830-9b8877c4b656.png)

```tex
\begin{tabular}{c|c|c}
    集合论 & 类型论 & 范畴论 \\
    集合 & 类型 & 对象 \\
    元素 & 实例 & 态射 \\
    命题 & 满足某个关系的类型 & [[子对象分类器|意象]]
\end{tabular}
```

**Comment by abccsss** [comment]
像 LaTeX 一样, `& [` 和 `\\ [` 会被认为是可选参数, 需要写 `&{} [[...]]`.

不过我有空来修复.

**Comment by ice1000** [comment]
草
