### ISSUE TITLE
bibtex 部分后缀的人名能加链接吗？

### ISSUE THREAD

**Issue by ice1000** [banana-space/btex#29]
比如我说一个人叫 `[[Jobs Jr., Steve]]`，这个链接能变成对 `[[Steve Jobs Jr.]]` 这个名字的引用吗？

**Comment by abccsss** [comment]
能啊，为什么要开 issue...

**Comment by ice1000** [comment]
> 能啊，为什么要开 issue...

就是想问一下，刚才人在手机上。不好意思。
