### ISSUE TITLE
code或codeblock环境内对大括号和%符号的识别

### ISSUE THREAD

**Issue by rqy2002** [banana-space/btex#31]
如题，否则编译器无法识别环境的结束。

但是有可能存在这种情况：
```text
\codeblock*{
  for (int i = 1; i <= n; i++) { a[i] = b[i] % c[i]; }
}
```
这种情况下 btex 会忽略 % 符号后的右大括号并报错：大括号未匹配。
既然codeblock中所有符号都会渲染，这样的处理是否是一种 bug？

**Comment by abccsss** [comment]
目前可以用 `#{` 和 `#}` 来 escape 大括号，暂时规避这个问题。

不过这确实是 bug，应该修复。

**Comment by abccsss** [comment]
我感觉可能增加 `#%` 来 escape 百分号能比较方便地解决问题，不会破坏 btex 的大括号优先的解析原则。

**Comment by abccsss** [comment]
相关已知 bug：
``` latex
\codeblock{
    1 % 第一行
    2 % 第二行
}
```
第二行注释不会显示。
