### ISSUE TITLE
`\vec` 在行间公式不显示

### ISSUE THREAD

**Issue by Trebor-Huang** [banana-space/btex#7]
看了一下，KaTeX接收到了这个参数并且生成了对应的html，所以不是parsing或者其他解析问题

**Comment by Trebor-Huang** [comment]
在行内公式显示正常

**Comment by Trebor-Huang** [comment]
应该是香蕉空间css的问题，那可以把这个issue migrate过去

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/214941346-ec0ccea6-98c2-4271-96c2-160d769ba3c1.png)

感觉扩大一点公式的高度就可以了

**Comment by Trebor-Huang** [comment]
不行， $(\vec A)^2$ 仍然不会显示

**Comment by abccsss** [comment]
看起来是 CSS 的问题，已经在[主项目](https://github.com/banana-space/banana-space/commit/0665cd13c7337ee7939c80fdaae3f6e276a8e0d7)解决
